# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20170425_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='alias',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.TextField(default='user', max_length=100),
            preserve_default=False,
        ),
    ]
